name: payday_flutter
description: AI 기반 스마트 수익 창출 플랫폼

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6

  # HTTP & API
  dio: ^5.4.0

  # Local Storage & Cache
  shared_preferences: ^2.2.2
  path: ^1.8.3
  connectivity_plus: ^7.0.0

  # Share functionality
  share_plus: ^12.0.0

  # File handling and CSV export
  csv: ^6.0.0
  path_provider: ^2.1.2
  file_picker: ^8.1.6

  # Charts and visualization
  fl_chart: ^1.1.1

  # Push notifications
  flutter_local_notifications: ^19.4.2
  permission_handler: ^12.0.1
  timezone: ^0.10.1

  # Cloud Storage
  supabase_flutter: ^2.8.0
  flutter_secure_storage: ^9.2.2
  intl: ^0.20.2

  # Firebase
  firebase_core: ^3.15.2
  firebase_analytics: ^11.3.6
  firebase_messaging: ^15.1.7
  firebase_auth: ^5.7.0

  # Social Login
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.3

  # Progress indicators
  percent_indicator: ^4.2.3

  # Ads
  google_mobile_ads: ^6.0.0
  dio_cookie_manager: ^3.3.0
  cookie_jar: ^4.0.8

  # Cryptography
  crypto: ^3.0.5

  # Biometric Authentication
  local_auth: ^2.3.0
  google_fonts: ^6.3.2
  flutter_animate: ^4.5.2
  go_router: ^16.2.4
  provider: ^6.1.5+1
  app_tracking_transparency: ^2.0.6+1

  # 걷기 측정
  pedometer: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"