# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install app dependencies
RUN npm cache clean --force
RUN npm ci

RUN apk add --no-cache build-base python3
RUN which python3

# Copy the rest of the application's code
COPY . .

# The app binds to port 3000, no need to expose here, docker-compose handles it
CMD [ "node", "server.js" ]
